dacs/dacs/Controllers/Post_TypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dacs.Models;

namespace dacs.Controllers
{
    public class Post_TypeController : Controller
    {
        private dbphongtromodels db = new dbphongtromodels();

        // GET: Post_Type
        public ActionResult Index()
        {
            return View(db.Post_Type.ToList());
        }

        // GET: Post_Type/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post_Type post_Type = db.Post_Type.Find(id);
            if (post_Type == null)
            {
                return HttpNotFound();
            }
            return View(post_Type);
        }

        // GET: Post_Type/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Post_Type/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "P_TypeID,P_TypeName,P_Desciption")] Post_Type post_Type)
        {
            if (ModelState.IsValid)
            {
                db.Post_Type.Add(post_Type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post_Type);
        }

        // GET: Post_Type/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post_Type post_Type = db.Post_Type.Find(id);
            if (post_Type == null)
            {
                return HttpNotFound();
            }
            return View(post_Type);
        }

        // POST: Post_Type/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "P_TypeID,P_TypeName,P_Desciption")] Post_Type post_Type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post_Type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post_Type);
        }

        // GET: Post_Type/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post_Type post_Type = db.Post_Type.Find(id);
            if (post_Type == null)
            {
                return HttpNotFound();
            }
            return View(post_Type);
        }

        // POST: Post_Type/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Post_Type post_Type = db.Post_Type.Find(id);
            db.Post_Type.Remove(post_Type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dacs/dacs/Views/Shared/Admin.cshtml
<!--<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@ViewData["Title"]</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="shortcut icon" type="image/icon" href="~/images/logo.ico" />
    @RenderSection("Header", required: false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-action="Index" asp-controller="Home" class="nav-link">Trang chủ</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Liên hệ</a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#" style="background-color:#63B8FF;">
                        <i class="fa fa-cog"></i> Tùy chọn
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <!-- Message Start -->
                        <div>
                            <a asp-action="Index" asp-controller="Home" class="dropdown-item dropdown-footer">Trang chủ</a>
                        </div>
                        <!-- Message End -->
                        <div>
                            <a asp-action="ChangePass" asp-controller="Admin" class="dropdown-item dropdown-footer">Đổi mật khẩu</a>
                        </div>
                        <a asp-action="Login" asp-controller="Login" class="dropdown-item dropdown-footer text-white" style="background-color:#63B8FF;">Đăng xuất</a>

                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="color:#7C7D7D;">
            <!-- Brand Logo -->
            <a asp-action="Index" asp-controller="Home" class="brand-link text-light" style="background-color:#7C7D7D;">
                <img src="~/images/logo.png" alt="Trang chủ Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text text-light"><strong>Ứng dụng Tìm P.trọ</strong></span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="~/POSTs/Index" style="background-color:#FC5677;">
                                <i class="nav-icon far fa-user"></i>
                                <p>
                                    Người quản trị
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview menu-open">
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Posts" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Bài đăng </p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Post_Type" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Loại bài đăng</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Users" class="nav-link bg-warning">
                                <i class="fas fa-user nav-icon"></i>
                                <p style="color:white;">Nhóm người dùng</p>
                            </a>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link" style="background-color:lightseagreen;">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Vị trí, địa lý
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="ProvinceCitys" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Tỉnh, thành phố</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="districts" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Huyện</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Wards" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Khu vực</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div><!-- /.container-fluid -->
    </div> <!-- /.content-wrapper -->
    <!-- Main Footer -->
    <footer class="main-footer" style="margin:0px;">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <!-- Bootstrap 4 -->
   
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

dacs/dacs/Views/Shared/View.cshtml
@model IEnumerable<dacs.Models.Post_Image>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.POST.POST_TITLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_ImageContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_ImageIndex)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.POST.POST_TITLE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_ImageContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P_ImageIndex)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.P_ImageID }) |
            @Html.ActionLink("Details", "Details", new { id=item.P_ImageID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.P_ImageID })
        </td>
    </tr>
}

</table>

dacs/dacs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

dacs/dacs/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta id="myViewport" name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/UserUI/Author.css" rel="stylesheet" />
    <script src="~/Scripts/UserUI/menu-account.js"></script>
    @RenderSection("header", false)
</head>
<body>
    <div id="navbarTop">
        @if (Session["User"] != null)
        {
            var user = Session["User"] as dacs.Models.ADMIN;
            <div class="dropdown" style="float:right;" id="dropdown">
                <div class="dropbtn">Xin chào: @user.ADMIN_FULL_NAME <i class="fa fa-unsorted"></i></div>
                <div class="dropdown-content" id="dropdown-content">
                    <a href="/">Trang chủ</a>
                    <a href="/doi-mat-khau">Đổi mật khẩu</a>
                    <a href="/dang-tin-moi">Đăng tin mới</a>
                    <a href="/userPost/logout">Đăng xuất</a>
                </div>
            </div>
        }
        else
        {
            <div class="user">
                <a rel="nofollow" class="link" href="/dang-nhap-tai-khoan">Đăng nhập</a>
                <a rel="nofollow" class="link" href="/dang-ky-tai-khoan"> Đăng ký</a>
                <a rel="nofollow" class="link" href="/dang-tin-moi"> Đăng tin mới</a>
            </div>
            <div class="options" id="options" onclick="menu()">
                <img src="https://image.flaticon.com/icons/png/128/118/118756.png" width="100%" height="100%">
                <div class="menu">
                    <ul class="sub-menu" id="sub-menu">
                        <li>
                            <a class="links" href="/dang-nhap-tai-khoan">Đăng nhập</a>
                        </li>
                        <li>
                            <a class="links" href="/dang-ky-tai-khoan"> Đăng ký</a>
                        </li>
                        <li>
                            <a class="links" href="/dang-tin-moi"> Đăng tin mới</a>
                        </li>
                    </ul>
                </div>
            </div>
        }
        <div class="clear"></div>
    </div>
    <div id="welcome">
        <div class="logo">
            <img src="~/Images/logo.png" alt="Phòng trọ online" height="100%" width="100%"></img>
        </div>
        <div class="adverti">
            <img src="https://bandon.vn/uploads/logo-ngang-1000x400.jpg" alt="Thông tin quảng cáo" height="100%" width="100%"></img>
        </div>
    </div>
    @RenderBody()
    <footer>
        <div id="footer">
            <div class="container">
                <div class="footer-info">
                    <div class="w980">
                        <p class="footer-title">
                            <strong>THÔNG TIN TRANG WEB</strong>
                        </p>
                        <p>
                            <strong>Tổng đài CSKH: 0999.990.999</strong>
                        </p>
                        <p>Copyright ©2019 timphongtroonline.com</p>
                        <p>Email: cskh.timphongtroonline@gmail.com | lienhe.timphongtroonline@gmail.com</p>
                        <p>Địa chỉ:  Quận 2, Tp. Hồ Chí Minh.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("footer", false)
    <script src="~/Scripts/UserUI/menu_login.js"></script>
</body>
</html>

dacs/dacs/Views/Shared/_LayoutPost.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta id="myViewport" name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/UserUI/post.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @RenderSection("header", false)
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/UserUI/menu-account.js"></script>
</head>
<body>
    <div id="navbarTop">
        <div class="clear"></div>
    </div>
    <div id="welcome">
        <div class="logo">
            <img src="~/Images/logo.png" alt="Phòng trọ online" height="100%" width="100%"></img>
        </div>
        <div class="adverti">
            <img src="https://bandon.vn/uploads/logo-ngang-1000x400.jpg" alt="Thông tin quảng cáo" height="100%" width="100%"></img>
        </div>
    </div>
    @RenderBody()
    <footer>
        <div id="footer">
            <div class="container">
                <div class="footer-info">
                    <div class="w980">
                        <p class="footer-title">
                            <strong>THÔNG TIN TRANG WEB</strong>
                        </p>
                        <p>
                            <strong>Tổng đài CSKH: 0999.990.999</strong>
                        </p>
                        <p>Copyright ©2019 timphongtroonline.com</p>
                        <p>Email: cskh.timphongtroonline@gmail.com | lienhe.timphongtroonline@gmail.com</p>
                        <p>Địa chỉ:  Quận 2, Tp. Hồ Chí Minh.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("footer", false)
    <script src="~/Scripts/UserUI/menu_login.js"></script>
</body>
</html>

dacs/dacs/Views/Shared/_Layoutindex.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="~/Content/UserUI/indexhome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/UserUI/menu-account.js"></script>
    @RenderSection("header", false)
</head>
<body>
    <div id="navbarTop">
        @if (Session["User"] != null)
        {
            var user = Session["User"] as dacs.Models.ADMIN;
            <div class="dropdown" style="float:right;" id="dropdown">
                <div class="dropbtn">Xin chào: @user.ADMIN_FULL_NAME <i class="fa fa-unsorted"></i></div>
                <div class="dropdown-content" id="dropdown-content">
                    <a href="/">Trang chủ</a>
                    <a href="/doi-mat-khau">Đổi mật khẩu</a>
                    <a href="/dang-tin-moi">Đăng tin mới</a>
                    <a href="/userPost/logout">Đăng xuất</a>
                </div>
            </div>
        }
        else
        {
            <div class="user">
                <a rel="nofollow" class="link" href="/dang-nhap-tai-khoan">Đăng nhập</a>
                <a rel="nofollow" class="link" href="/dang-ky-tai-khoan"> Đăng ký</a>
                <a rel="nofollow" class="link" href="/dang-tin-moi"> Đăng tin mới</a>
            </div>
            <div class="options" id="options" onclick="menu()">
                <img src="https://image.flaticon.com/icons/png/128/118/118756.png" width="100%" height="100%">
                <div class="menu">
                    <ul class="sub-menu" id="sub-menu">
                        <li>
                            <a class="links" href="/dang-nhap-tai-khoan">Đăng nhập</a>
                        </li>
                        <li>
                            <a class="links" href="/dang-ky-tai-khoan"> Đăng ký</a>
                        </li>
                        <li>
                            <a class="links" href="/dang-tin-moi"> Đăng tin mới</a>
                        </li>
                    </ul>
                </div>
            </div>
        }
        <div class="clear"></div>
    </div>
    <div id="welcome">
        <div class="logo">
            <img src="~/Images/logo.png" alt="Phòng trọ online" height="100%" width="100%"></img>
        </div>
        <div class="adverti">
            <img src="https://bandon.vn/uploads/logo-ngang-1000x400.jpg" alt="Thông tin quảng cáo" height="100%" width="100%"></img>
        </div>
    </div>
    <div id="main">
        <div id="searchbar">
            <div class="container">
                <form id="searchformTop" novalidate="novalidate" action="/UserUI/FindPost" method="post">
                    <div class="search_field">
                        <div class="clearfix">
                            <div class="search_field_item">
                                <label class="search_field_item_label">Địa chỉ</label>
                                <input name="duong" class="select-option" placeholder="Nhập địa chỉ cần tìm">
                            </div>
                            <div class="search_field_item">
                                <label class="search_field_item_label">Tỉnh thành phố</label>
                                <select id="search_city" class="select-option" name="tinh"></select>
                            </div>
                            <div class="search_field_item">
                                <label class="search_field_item_label">Quận huyện</label>
                                <select id="district" class="select-option" name="quan">
                                    <option value="0">-- Chọn quận/ huyện --</option>
                                </select>
                            </div>
                            <div class="search_field_item">
                                <label class="search_field_item_label">&nbsp;</label>
                                <button type="submit" class="btn_search_box"> Tìm kiếm </button>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <footer>
        <div id="footer">
            <div class="container">
                <div class="footer-info">
                    <div class="w980">
                        <p class="footer-title">
                            <strong>THÔNG TIN TRANG WEB</strong>
                        </p>
                        <p>
                            <strong>Tổng đài CSKH: 0999.990.999</strong>
                        </p>
                        <p>Copyright ©2019 timphongtroonline.com</p>
                        <p>Email: cskh.timphongtroonline@gmail.com | lienhe.timphongtroonline@gmail.com</p>
                        <p>Địa chỉ:  Quận 2, Tp. Hồ Chí Minh.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("footer", false)
    <script src="~/Scripts/UserUI/menu_login.js"></script>
    <script src="~/Scripts/UserUI/loaddiswar.js"></script>
</body>
</html>